### ISSUE TITLE
Pls give .env fields

### ISSUE THREAD

**Issue by creativetechify** [prashmi24/Cure#1]
Pls give me the .env fields which have to add at frontend and backend

**Comment by prashmi24** [comment]
It contains sensitive information, configurations and passwords. Also, each one is different so I can't share.

**Comment by creativetechify** [comment]
i mean pls tell me what fileds are required, for exmaple MONGO_URI = "YOUR URL HERE'

pls tell all fields like this

**Comment by prashmi24** [comment]
Sure, here you go- PORT, MONGO_URL, JWT_SECRET_KEY
